
version: "3.9"
services:
  techzone_back:
    depends_on:
      - mysqlito
    build: .
    env_file:
      - ./.env
    ports:
      - $PORT:8080
    environment:
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DIALECT=$DB_DIALECT
      - DB_HOST=$DB_HOST
      - SECRET=$SECRET
      - NODE_VERSION=$NODE_VERSION
      - API_KEY=$API_KEY
      - AUTH_DOMAIN=$AUTH_DOMAIN
      - PROJECT_ID=$PROJECT_ID
      - STORAGE_BUCKET=$STORAGE_BUCKET
      - MESSAGING_SENDER_ID=$MESSAGING_SENDER_ID
      - APP_ID=$APP_ID
      - MEASUREMENT_ID=$MEASUREMENT_ID
      - MAILER_PASSWORD=$MAILER_PASSWORD
      - MAILER_USER=$MAILER_USER
    links:
      - mysqlito
  mysqlito:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=techzone
      - MYSQL_PASSWORD=123
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_RANDOM_ROOT_PASSWORD=no